name: Nightly Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  update_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.10'
        environment-file: environment.yml
        activate-environment: myenv

    - name: Install yfinance and requests with pip
      shell: bash -l {0}
      run: |
        pip install yfinance requests

    - name: Run script
      shell: bash -l {0}
      run: |
        conda info
        python generate_indicator.py

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add images/
        git commit -m "Update VIX indicator images"
        # Use the REPO_ACCESS_TOKEN for authentication
        git push https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/nightvision04/ivol-t-indicator.git HEAD:main
